general:
   debug_on: False
   logging_level: "WARNING" # switch to control logging - WARNING for full logging; ERROR to minimize logging
file_names:
   pipeline1_filename: sc_delay_pipeline_dec27b.pkl
   pipeline2_filename: sc_delay_pipeline_keras_prep_dec27b.pkl
   model_filename: scmodeldec27b_5.h5
   